### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by tarsius**

### CODE REVIEW

**Comment by tarsius** [comment]
Every few months I run the spell checker on all the packages I have installed and fix the new typos.
In this case I ended up fixing the same typos again, so I thought I would send this friendly ping.

Ping!

**Comment by twmr** [comment]
@tarsius can we move this to the emacs-orphanage project somehow, because the owner of the repo is unfortunately no longer working on his open source emacs packages.

**Comment by tarsius** [comment]
From the looks of it, this would be a good candidate, but we'll have to talk to Andreas about it first. (Among other things we would like him to transfer the repository instead of us forking it and loosing all issues and pull-requests in the process.)

However I am on a break and try to avoid most work, especially bureaucratic work. After I get back from my break I will go through all notifications, but I won't start with that for at least another month and then it won't be done in a few days either. Please ping me in about two months if you haven't heard back from me by then.

Meanwhile, could you point me to any issues/readmes where Andreas states that he has stopped working on these packages and whether he is looking for successors.

**Comment by twmr** [comment]
Take your time. I'll ping you in a couple of months (if I don't forget)

> Meanwhile, could you point me to any issues/readmes where Andreas states that he has stopped working on these packages and whether he is looking for successors.

No, AFAIK he didn't mention it anywhere. I know that @vedang has created a fork of one of his most popular projects (pdf-tools) that he is currently maintaining and which is also used now in MELPA as the source of the `pdf-tools` pkg.

**Comment by Thaodan** [comment]
> From the looks of it, this would be a good candidate, but we'll have to talk to Andreas about it first. (Among other things we would like him to transfer the repository instead of us forking it and loosing all issues and pull-requests in the process.)
> 
> However I am on a break and try to avoid most work, especially bureaucratic work. After I get back from my break I will go through all notifications, but I won't start with that for at least another month and then it won't be done in a few days either. Please ping me in about two months if you haven't heard back from me by then.
> 
> Meanwhile, could you point me to any issues/readmes where Andreas states that he has stopped working on these packages and whether he is looking for successors.

Any update on this?

**Comment by tarsius** [comment]
I'm now willing to do my part.

I would still prefer if @politza transferred the repository. @thisch have you tried contacting him by mail?

**Comment by twmr** [comment]
> I'm now willing to do my part.
> 
> I would still prefer if @politza transferred the repository. @thisch have you tried contacting him by mail?

No I haven't yet tried contacting him, but someone else did (see 
https://github.com/politza/pdf-tools/issues/659#issuecomment-779447118) but without success.

**Comment by tarsius** [comment]
Sounds like waiting for him to transfer or otherwise respond wouldn't do much good.

@thisch so if I understand this correctly, you are volunteering to maintain this under the umbrella of the orphanage. Shall I setup the repository and invite you?

**Comment by twmr** [comment]
@tarsius  Yes, please invite me. Thx

**Comment by tarsius** [comment]
Thanks! Invite is on its way.

**Comment by tarsius** [comment]
Closing since this is now maintained [in the orphanage](https://github.com/emacsorphanage/tablist).

**Comment by marsam** [comment]
Hi, I'm also interested in maintaining this package. 
I have a few changes in my fork https://github.com/politza/tablist/compare/master...emacs-pe:tablist:master and I can work in fixes.
Shall I send my changes to your fork?

**Comment by tarsius** [comment]
> Hi, I'm also interested in maintaining this package.

Do you have experience maintaining Emacs packages. @thisch how do you feel about a co-maintainer.

> Shall I send my changes to your fork?

Let's begin with a pull-request, yes. Do you have plans for future work, that you didn't work on so far because of the prospect of not being able to get them merged?

**Comment by twmr** [comment]
Having a co-maintainer is fine for me, actually this would very much appreciated.

Yes, please start submitting pull-requests.

**Pull request closed without merging**
